spring:
  application:
    name: boot-prom-compose
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  prometheus:
    metrics:
      export:
        enabled: true